name: Deploy image on VPS server

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  deploy:
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Create key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/private.key
          chmod 600 ~/.ssh/private.key
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}

      - name: Connect via SSH
        run: |
          ssh -i "$SSH_KEY_PATH" "$SSH_USER@$SSH_HOST"
        shell: bash
        env:
          SSH_KEY_PATH: ~/.ssh/private.key
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
