name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.13]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Create data.json
        run: |
          mkdir -p src/data
          echo "${{ secrets.DATA_JSON }}" | base64 -d > src/data/data.json

      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
